name: Craftorio
version: '0.01'
main: me.sucukya.craftorio.Craftorio
api-version: '1.21'
load: STARTUP
authors: [Sucukya]
description: Factorio-like Factory for Minecraft
commands:
  gm:
    usage: /gm <1,2,3,0>
    description: Better Game Mode command.